// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxzvobiekgkrtoxlykjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4enZvYmlla2drcnRveGx5a2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Mjg2ODksImV4cCI6MjA2NTIwNDY4OX0.muO3UcuVrPs8XBy8TGTUt6ex_B7aHSKW65t5TEIJYhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);